{% set name = "plot_nucmer" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0

requirements:
  host:
    - bash
    - mummer
    - samtools
    - r
    - r-base
  run:
    - bash
    - mummer
    - samtools
    - r
    - r-base

about:
  home: "https://github.com/fmalmeida/plot_nucmer"
  license: GPL-3
  license_family: GPL-3
  license_file:
  summary: "A simple script to run an alignment with nucmer and visualise its results."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - fmalmeida
